obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
#ifdef CONFIG_PRODUCT_REALME_RMX1805
obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/
#endif /* CONFIG_PRODUCT_REALME_RMX1805 */
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/
#ifdef CONFIG_PRODUCT_REALME_RMX1805
obj-y     +=  oppo_healthinfo/
#endif /* CONFIG_PRODUCT_REALME_RMX1805 */
